[package]
name = "workshop"
version = "0.1.0"
authors = ["NikVolf <nikvolf@gmail.com>"]

[dependencies]
tiny-keccak = "1.3"
bigint = { version = "4.2", features = ["std"] }

[[bin]]
path = "src/main.rs"
name = "workshop"